### ISSUE TITLE
3.5 Exercises 2

### ISSUE THREAD

**Issue by yutokyokutyo** [yutokyokutyo/sample_app#3]
## 3.5 Exercises 2

> http://www.railstutorial.org/book/static_pages#sec-static_pages_exercises

`spec/requests/static_pages_spec.rb`について、Let関数を使い重複を阻止しました。

MaterにMergeしたいのですが、レビューをお願いいたします。
### 動作確認

![2014-07-09 18 16 41](https://cloud.githubusercontent.com/assets/7356977/3522204/cf1741ba-0749-11e4-878f-9345e4108483.png)
- Greenを確認しました。

@tacahilo @kitak @gs3 @keokent

**Comment by hfm** [comment]
このIssueはなんだろう :question:

**Comment by ravelll** [comment]
プルリクと間違えて立てたのかな？
必要なければ close してしまおう〜

**Comment by yutokyokutyo** [comment]
このissueは必要ないですね！
closeします！！
